docs/1_Introduction.md, docs/4_Mikado_Method_to_the_Rescue.md, docs/Troubleshooting.md, src/main/cpp/bin/Application.cpp, src/main/cpp/lib/Invoice.cpp, src/main/cpp/lib/JsonRepository.cpp, src/main/cpp/lib/Novel.cpp, src/main/cpp/lib/domain/book/Novel.h, src/test/cpp/Tests.cpp, src/test/cpp/storage/InMemoryRepository.h, src/test/cpp/testbuilders-workshop-tests.vcxproj, src/test/cpp/testbuilders-workshop-tests.vcxproj.filters, testbuilders-workshop.sln
To help C++ participants to run the workshop without losing time
- Add instructions to load the code
- Throw explicit error when C++ version does not find data file
- Remove the bug fix from Invoice.cpp
- Add disabled test placeholder
- Provide C++ code snippets from mikado video
I'd rather not squash this PR!
=> Improve C++ environment and animation guide

README.md
Hey there, 
I forgot to update this section as part of the PR...I would be proud to have my name next to yours, is that OK?
=> Add Christophe Cadilhac as a contributor

cpp/src/lib/JsonRepository.cpp, cpp/src/resources/repository.json, docs/1_Introduction.md, docs/2_Easy_Fix_Difficult_Test.md
1. Change the paths of some source code files in the MD files to ensure
the GitHub pages are working properly
2. Add the file 'repository.json' under the 'src/resources' folder for
the Cpp code
3. Change the reference in the Application.cpp to point to the new Json
file
=> Fix the reference paths for MD and CPP files

docs/1_Introduction.md, docs/4_Mikado_Method_to_the_Rescue.md, docs/Animation_Guide.md
To make it ready for a larger audience
=> Update instructions to use mobs instead of pairs

java/BUILD_MANUAL.md, java/build.gradle, java/pom.xml, java/src/main/java/com/murex/tbw/storage/JsonRepository.java
In order to provide attendees with a build manual for the Java version.
1. Add the BUILD_MANUAL.md under the java folder
2. Modify the pom.xml and build.gradle files to allow generating an executable jar file on build
=> Write a Java Build Manual 

csharp/Application.Tests/Purchase/InvoiceTest.cs, csharp/Application.Tests/Report/ReportGeneratorTest.cs, csharp/Application/Purchase/Invoice.cs, csharp/Application/Report/ReportGenerator.cs, java/src/main/java/com/murex/tbw/purchase/Invoice.java, java/src/main/java/com/murex/tbw/report/ReportGenerator.java, java/src/test/java/com/murex/tbw/purchase/InvoiceTest.java, java/src/test/java/com/murex/tbw/report/ReportGeneratorTest.java
This will ease the work of the attendees and speed up the phases where they should not be spending too much time.
=> Add unit test samples and commented bugfixes

cpp/BUILD_MANUAL.md, cpp/CMakeLists.txt, cpp/cmake/CPM.cmake, cpp/cmake/FindGoogleTest.cmake, cpp/cpp_setup.sh, cpp/cpp_setup_win.bat, cpp/src/lib/Author.cpp, cpp/src/lib/Book.cpp, cpp/src/lib/BooksOrder.cpp, cpp/src/lib/Client.cpp, cpp/src/lib/Country.cpp, cpp/src/lib/CurrencyConverter.cpp, cpp/src/lib/EducationalBook.cpp, cpp/src/lib/IdGenerator.cpp, cpp/src/lib/Invoice.cpp, cpp/src/lib/JsonRepository.cpp, cpp/src/lib/MainRepository.cpp, cpp/src/lib/Novel.cpp, cpp/src/lib/Order.cpp, cpp/src/lib/PurchasedBook.cpp, cpp/src/lib/ReportGenerator.cpp, cpp/src/lib/Repository.cpp, cpp/src/lib/TaxRule.cpp, cpp/tests/Tests.cpp, docs/2_Easy_Fix_Difficult_Test.md
- Add the solution as Commented Code in the two functions ReportGenerator::getTotalAmount & purchase::Invoice::computeTotalAmount() 
- Add a function to get the rounded value of the total amount 
- Create empty C++ Tests for users
=> Apply fixes to the CPP Version to be aligned with Java & C# 

docs/Facilitation_Guide.md, docs/Homework.md
So that it's a ready made email
- add absolute http links
- add links to the reference web centers
- add a link and a short text from the facilitation guide to the
homework
- Minor text updates to the homework
=> Improvement to the homework communication template

docs/Homework.md
So that we can cut and paste the homework for connection message
- update github folder links with tree/master/
- update github file links with blob/master/
=> Fix links in the homework file

docs/facilitation/Remote.md
So that we all know how to handle this kind of event through MS Teams
- add a tip about breakout rooms
- tip about extra channels for help and notifications
=> Add a section about MS Teams best practices

docs/facilitation/Remote.md
So that we don't forget to mention anything
- add the outline to the remote facilitation guide
- did not do it for the colocalized guide yet
Main question: did I forget anything?
=> Write outline for the intro script when remote

cpp/src/lib/Invoice.cpp, cpp/src/lib/ReportGenerator.cpp, docs/facilitation/2h.md
1. Provide the fix in C++ by Defaults
2. Keep the bug in the code while being commented.
=> In-order to make it faster for attendees to finish the first iteration

java/src/main/java/com/murex/tbw/purchase/Invoice.java, java/src/main/java/com/murex/tbw/report/ReportGenerator.java
- Provide the fix in Java by Deafult
- Keep the bug in the code while being commened
=> In order to make it faster for attendees to finish the first iteration

cpp/BUILD_MANUAL.md, docs/1_Introduction.md, docs/Troubleshooting.md, java/BUILD_MANUAL.md
1. Update the Introduction.md file to reference the Build Manuals
2. Add more content to the TroubleShooting to reference the Actions in case compilation is not working
=> Update the Troubleshooting Guide 

.github/workflows/cmake.yml, .github/workflows/gradle.yml, .github/workflows/maven.yml
Update the "on" section in the 3 yml files to include: 
1. Push on master 
2. PullRequests to master
=> In order to prevent Github Actions from running on branches ending with "from-video"

csharp/Application/Purchase/Invoice.cs, csharp/Application/Report/ReportGenerator.cs
In order to make it faster for attendees to finish the first iteration.
This is the C# version of https://github.com/murex/mikado-testbuilders-kata/pull/43
=> C#: Provide the code already fixed

cpp/BUILD_MANUAL.md, java/BUILD_MANUAL.md
- Add a section for running the application from IntelliJ
- Set the total amount to 424.57
=> In order to update the Build Manuals with the right numbers

csharp/BUILD_MANUAL.md, docs/1_Introduction.md, docs/Homework.md
To catch up with the Java and C++ bits.
=> Add the C# build manual

docs/Homework.md
To make english better
- fix typos
- make text on a single line
=> Minor text fixes to the homework file

docs/facilitation/2h.md
Timers and notification timetable for 2 hours
So that we know exactly what to do at what time during the workshop, and that eventually, we finish the workshop on time
- add notes about when to start the timer
- add notes about what notifications to send
=> Detailed timetable

docs/facilitation/2h.md, docs/facilitation/Remote.md
To make sure we attendees understand how the workshop will be run
- follow the miro boxes
- timer to jump to next activity
- take time for mini-retros
- don't try to save time on team-building
- mob roles
=> Add details to the instructions

.github/workflows/cmake.yml, .github/workflows/contributors.yml, .github/workflows/gradle.yml, .github/workflows/maven.yml, README.md
- Renamed the Github Actions 
- Added the status of the actions to the ReadMe file
=> Add build tags to the ReadMe file

README.md, docs/1_Introduction.md, docs/2_Easy_Fix_Difficult_Test.md, docs/3_Building_Test_Data.md, docs/4_Mikado_Method.md, docs/5_Mikado_Method_plus_Test_Data_Builders.md, docs/Homework.md, kotlin/BUILD_MANUAL.md, kotlin/src/test/kotlin/com/murex/tbw/report/ReportGeneratorTest.kt, kotlin/src/test/kotlin/com/murex/tbw/storage/InMemoryRepository.kt
Following the creation of the Kotlin version, we need to update the doc files to include a reference to the Kotlin code. 
This PR includes: 
1. Update of the README file
2. Update of the files under the doc folder 
3. Adding 2 missing Kotlin files (ReportGeneratorTest.kt and InMemoryRepository.kt)
=> Update the doc files to include reference the Kotlin version

cpp/cmake/FindGoogleTest.cmake
=> Switch branch from master to main in C++ FindGoogleTest.cmake

.github/workflows/gradle.yml, .github/workflows/maven.yml, cpp/CMakeLists.txt, cpp/cmake/FindGoogleTest.cmake, cpp/cpp_setup.sh, cpp/cpp_setup_win.bat, java/build.gradle, java/pom.xml
Upgrade the Java version from 8 to 17 
- Update the Java version in the Pom & Gradle files 
- Update the workflow yaml files 
Upgrade CMake to 3.26.2
Fixes #(issue)
Please tick the appropriate option using [x]
Please tick the appropriate options using [x]
- [] My PR includes tests that cover my code changes.
=> Upgrade Java & CMake
